//! The aprsr status dashboard and JSON API.
//!
//! The dashboard is server-rendered with [Askama] and kept live with HTMX: each panel
//! polls its own fragment endpoint and swaps itself in place. That keeps the client-side
//! JavaScript to a few dozen lines and means the page is complete and readable on first
//! paint, with no JavaScript at all.
//!
//! Static assets are **compiled into the binary** from `static/`, which is generated by the
//! npm build and committed. That is what lets `cargo run` produce a styled page on a machine
//! with no Node toolchain — and what lets the binary be copied to a server, or into a
//! container, and still have one. See [`assets`] and `AGENTS.md`.
//!
//! [Askama]: https://askama.rs/

pub mod assets;
pub mod format;
pub mod metrics_text;
pub mod routes;
pub mod sse;
pub mod status;
pub mod view;

use std::net::SocketAddr;
use std::sync::Arc;

use actix_web::{App, HttpServer, web};
use aprsr_server::ServerState;

pub use status::Status;

/// Why the web interface could not start.
#[derive(Debug, thiserror::Error)]
pub enum WebError {
    #[error("could not bind the status server to {address}: {source}")]
    Bind {
        address: SocketAddr,
        #[source]
        source: std::io::Error,
    },
    #[error("status server failed: {0}")]
    Run(#[source] std::io::Error),
}

/// Build the Actix application factory.
///
/// Exposed so tests can mount the same routes with `actix_web::test` rather than binding a
/// socket.
pub fn configure(state: Arc<ServerState>) -> impl Fn(&mut web::ServiceConfig) + Clone {
    move |config: &mut web::ServiceConfig| {
        config
            .app_data(web::Data::from(Arc::clone(&state)))
            .service(routes::dashboard)
            .service(routes::status_json)
            .service(routes::healthz)
            .service(routes::fragment_summary)
            .service(routes::fragment_listeners)
            .service(routes::fragment_uplinks)
            .service(routes::fragment_clients)
            .service(routes::admin_reload)
            .service(routes::events_status)
            .service(routes::events_packets)
            .service(routes::metrics)
            .service(routes::api_history)
            .service(routes::config_json)
            .service(routes::api_stations)
            .service(routes::static_asset);
    }
}

/// Serve the dashboard until `shutdown` resolves.
pub async fn serve(
    address: SocketAddr,
    state: Arc<ServerState>,
    shutdown: impl Future<Output = ()> + Send + 'static,
) -> Result<(), WebError> {
    let configure = configure(state);
    let server = HttpServer::new(move || App::new().configure(configure.clone()))
        .disable_signals()
        .bind(address)
        .map_err(|source| WebError::Bind { address, source })?
        .run();

    let handle = server.handle();
    let serving = tokio::spawn(server);

    shutdown.await;
    tracing::info!("stopping the status server");
    handle.stop(true).await;

    match serving.await {
        Ok(result) => result.map_err(WebError::Run),
        Err(error) => {
            tracing::warn!(%error, "the status server task did not shut down cleanly");
            Ok(())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The committed assets are what make `cargo run` produce a styled page without Node.
    /// A missing one is now a compile error rather than a test failure — `include_bytes!`
    /// sees to that — so what is left to check is that every route is registered.
    #[test]
    fn every_embedded_asset_is_reachable() {
        for asset in assets::ASSETS {
            assert!(assets::find(asset.name).is_some());
        }
    }
}
