//! The aprsr status dashboard and JSON API.
//!
//! The dashboard is server-rendered with [Askama] and kept live with HTMX: each panel
//! polls its own fragment endpoint and swaps itself in place. That keeps the client-side
//! JavaScript to a few dozen lines and means the page is complete and readable on first
//! paint, with no JavaScript at all.
//!
//! Static assets are served from `static/`, which is **generated by the npm build and
//! committed**. That is what lets `cargo run` produce a styled page on a machine with no
//! Node toolchain; see `AGENTS.md`.
//!
//! [Askama]: https://askama.rs/

pub mod format;
pub mod routes;
pub mod status;
pub mod view;

use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::Arc;

use actix_web::{App, HttpServer, web};
use aprsr_server::ServerState;

pub use status::Status;

/// Why the web interface could not start.
#[derive(Debug, thiserror::Error)]
pub enum WebError {
    #[error("could not bind the status server to {address}: {source}")]
    Bind {
        address: SocketAddr,
        #[source]
        source: std::io::Error,
    },
    #[error("status server failed: {0}")]
    Run(#[source] std::io::Error),
}

/// Where the built dashboard assets live, relative to this crate.
#[must_use]
pub fn static_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("static")
}

/// Build the Actix application factory.
///
/// Exposed so tests can mount the same routes with `actix_web::test` rather than binding a
/// socket.
pub fn configure(state: Arc<ServerState>) -> impl Fn(&mut web::ServiceConfig) + Clone {
    move |config: &mut web::ServiceConfig| {
        config
            .app_data(web::Data::from(Arc::clone(&state)))
            .service(routes::dashboard)
            .service(routes::status_json)
            .service(routes::healthz)
            .service(routes::fragment_summary)
            .service(routes::fragment_listeners)
            .service(routes::fragment_clients);
    }
}

/// Serve the dashboard until `shutdown` resolves.
pub async fn serve(
    address: SocketAddr,
    state: Arc<ServerState>,
    shutdown: impl Future<Output = ()> + Send + 'static,
) -> Result<(), WebError> {
    let assets = static_dir();
    if !assets.is_dir() {
        // Not fatal: the API and the HTML still work, they just come through unstyled.
        tracing::warn!(
            path = %assets.display(),
            "dashboard assets are missing; run `make web` to build them"
        );
    }

    let configure = configure(state);
    let server = HttpServer::new(move || {
        App::new()
            .configure(configure.clone())
            .service(actix_files::Files::new("/static", static_dir()).prefer_utf8(true))
    })
    .disable_signals()
    .bind(address)
    .map_err(|source| WebError::Bind { address, source })?
    .run();

    let handle = server.handle();
    let serving = tokio::spawn(server);

    shutdown.await;
    tracing::info!("stopping the status server");
    handle.stop(true).await;

    match serving.await {
        Ok(result) => result.map_err(WebError::Run),
        Err(error) => {
            tracing::warn!(%error, "the status server task did not shut down cleanly");
            Ok(())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_static_directory_is_inside_this_crate() {
        let dir = static_dir();
        assert!(dir.ends_with("static"));
        assert!(
            dir.is_dir(),
            "crates/aprsr-web/static must exist and be committed; run `make web`"
        );
    }

    /// The committed assets are what make `cargo run` produce a styled page without Node.
    #[test]
    fn the_built_assets_are_committed() {
        let dir = static_dir();
        for asset in ["app.css", "app.js"] {
            let path = dir.join(asset);
            assert!(
                path.is_file(),
                "{} is missing; run `make web`",
                path.display()
            );
            let size = std::fs::metadata(&path).map(|m| m.len()).unwrap_or(0);
            assert!(size > 0, "{} is empty; run `make web`", path.display());
        }
    }
}
