//! The q construct algorithm.
//!
//! Every packet that enters APRS-IS gets a *q construct* appended to its path recording
//! how it got in: which kind of connection, and which station or server injected it. The
//! construct is what makes loop detection and entry-point attribution possible, and it is
//! what the `q/` and `e/` filters match against.
//!
//! Implemented from <http://www.aprs-is.net/qalgorithm.aspx> and
//! <http://www.aprs-is.net/q.aspx>. Rule-by-rule citations appear on
//! [`apply_client`].

use std::fmt;

use crate::packet::Tnc2Packet;
use crate::path::Path;

/// The q construct codes defined by APRS-IS.
///
/// The codes are case-sensitive: `qAo` and `qAO` are different constructs with different
/// meanings, so parsing and rendering both preserve case exactly.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum QCode {
    /// `qAC` — verified login via a bidirectional port, FROMCALL matching the login.
    /// The appended callsign identifies the receiving server.
    VerifiedClient,
    /// `qAX` — unverified login. Deprecated on APRS-IS; unverified clients may not
    /// inject data at all.
    Unverified,
    /// `qAU` — received over a direct UDP connection.
    Udp,
    /// `qAo` — packet gated by a client on a client-only port.
    GatedClientOnly,
    /// `qAO` — non-gated packet from a client-only port, or a send-only port packet
    /// whose FROMCALL matches the login.
    NonGated,
    /// `qAS` — from another server, or generated by a server itself.
    Server,
    /// `qAr` — from an IGate using the `,I` construct, reached through an intermediate
    /// server rather than directly.
    RemoteIgate,
    /// `qAR` — from an IGate using the `,I` construct over a verified direct connection.
    VerifiedIgate,
    /// `qAZ` — server-internal command packet. Must never propagate.
    Internal,
    /// `qAI` — trace. Each server appends its own identity.
    Trace,
}

impl QCode {
    /// The three-character wire form.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::VerifiedClient => "qAC",
            Self::Unverified => "qAX",
            Self::Udp => "qAU",
            Self::GatedClientOnly => "qAo",
            Self::NonGated => "qAO",
            Self::Server => "qAS",
            Self::RemoteIgate => "qAr",
            Self::VerifiedIgate => "qAR",
            Self::Internal => "qAZ",
            Self::Trace => "qAI",
        }
    }

    /// Parse a path hop as a q construct. Case-sensitive, as the specification requires.
    #[must_use]
    pub fn parse(hop: &str) -> Option<Self> {
        Some(match hop {
            "qAC" => Self::VerifiedClient,
            "qAX" => Self::Unverified,
            "qAU" => Self::Udp,
            "qAo" => Self::GatedClientOnly,
            "qAO" => Self::NonGated,
            "qAS" => Self::Server,
            "qAr" => Self::RemoteIgate,
            "qAR" => Self::VerifiedIgate,
            "qAZ" => Self::Internal,
            "qAI" => Self::Trace,
            _ => return None,
        })
    }
}

impl fmt::Display for QCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// A q construct located within a path.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FoundQ<'a> {
    pub code: QCode,
    /// Byte offset of the construct within the path string.
    pub offset: usize,
    /// The callsign immediately following the construct, if there is one.
    pub call: Option<&'a str>,
}

/// Locate the q construct in a path, if it has one.
#[must_use]
pub fn find(path: Path<'_>) -> Option<FoundQ<'_>> {
    let mut hops = path.hops();
    loop {
        let hop = hops.next()?;
        if let Some(code) = QCode::parse(hop.call) {
            return Some(FoundQ {
                code,
                offset: hop.offset,
                call: hops.next().map(|h| h.call),
            });
        }
    }
}

/// Why a packet must not be propagated.
///
/// From the "Packets to be rejected" rules at <http://www.aprs-is.net/qalgorithm.aspx>.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum QReject {
    #[error("packet carries qAZ and is server-internal")]
    Internal,
    #[error("packet carries qAC but never traversed a TCP client connection (no TCPIP marker)")]
    QacWithoutTcpip,
    #[error("loop: this server ({server_id}) already appears after the q construct")]
    Loop { server_id: String },
    #[error("loop: callsign {call} appears more than once in the path")]
    DuplicateInPath { call: String },
}

/// Everything the algorithm needs to know about the connection a packet arrived on.
#[derive(Debug, Clone, Copy)]
pub struct QContext<'a> {
    /// This server's own callsign — the `SERVERLOGIN` of the specification.
    pub server_id: &'a str,
    /// The callsign the sending client logged in as.
    pub login: &'a str,
    /// Whether the client presented a valid passcode.
    pub verified: bool,
    /// Whether the packet arrived over UDP rather than TCP.
    pub via_udp: bool,
    /// Whether the port is send-only (clients may transmit but receive nothing).
    pub send_only: bool,
}

/// The result of applying the algorithm: the construct in force and the resulting path.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct QOutcome {
    /// The q construct the packet now carries.
    pub code: QCode,
    /// The rewritten digipeater path. Feed this to [`Tnc2Packet::with_path`].
    pub path: String,
    /// Whether the path actually changed. When false the packet may be relayed as-is,
    /// which lets dispatch skip re-rendering the line.
    pub rewritten: bool,
}

/// Apply the client-to-server q algorithm.
///
/// The rules, in the order the specification states them at
/// <http://www.aprs-is.net/qalgorithm.aspx>:
///
/// 1. **Reject** `qAZ`, a `qAC` with no `TCPIP` marker, a path in which this server
///    already appears after the q construct, or a path with a repeated callsign-SSID.
/// 2. **UDP direct entry** — replace any existing construct with `qAU,SERVERLOGIN`, or
///    append it.
/// 3. **Unverified connection** — replace with `qAX,SERVERLOGIN`, or append it.
/// 4. **Trailing `,I` construct** — rewrite `,VIACALL,I` to `,qAR,VIACALL` when VIACALL
///    is the logged-in station, otherwise to `,qAr,VIACALL`.
/// 5. **Verified client, FROMCALL ≠ login** — downgrade an existing construct
///    (`qAR`/`qAr` → `qAo`; `qAS`/`qAC` → `qAO`), or append `qAO,login` if there is none.
/// 6. **Verified client, FROMCALL = login** — append `qAC,SERVERLOGIN`, or
///    `qAO,SERVERLOGIN` on a send-only port.
///
/// Note that this function does not enforce the separate APRS-IS policy that unverified
/// clients may not inject data at all — that is a connection-level decision made by the
/// server, which may prefer to drop the packet before it reaches the algorithm.
pub fn apply_client(packet: &Tnc2Packet<'_>, ctx: &QContext<'_>) -> Result<QOutcome, QReject> {
    let path = packet.path();
    let existing = find(path);

    // Rule 1 — rejection.
    if let Some(found) = existing {
        if found.code == QCode::Internal {
            return Err(QReject::Internal);
        }
        if found.code == QCode::VerifiedClient && !path.has_tcpip() {
            return Err(QReject::QacWithoutTcpip);
        }
        let loops_back = path
            .hops()
            .any(|h| h.offset > found.offset && h.call.eq_ignore_ascii_case(ctx.server_id));
        if loops_back {
            return Err(QReject::Loop {
                server_id: ctx.server_id.to_owned(),
            });
        }
    }
    if let Some(call) = path.first_duplicate() {
        return Err(QReject::DuplicateInPath {
            call: call.to_owned(),
        });
    }

    // Rule 2 — UDP direct entry.
    if ctx.via_udp {
        return Ok(replace_or_append(path, existing, QCode::Udp, ctx.server_id));
    }

    // Rule 3 — unverified connection.
    if !ctx.verified {
        return Ok(replace_or_append(
            path,
            existing,
            QCode::Unverified,
            ctx.server_id,
        ));
    }

    // Rule 4 — the legacy `,I` construct.
    if let Some(igate) = path.i_construct() {
        let code = if igate.eq_ignore_ascii_case(ctx.login) {
            QCode::VerifiedIgate
        } else {
            QCode::RemoteIgate
        };
        return Ok(rewrite_i_construct(path, code, igate));
    }

    let from_is_login = packet.source().eq_ignore_ascii_case(ctx.login);

    // Rule 5 — verified client relaying somebody else's packet.
    if !from_is_login {
        if let Some(found) = existing {
            let downgraded = match found.code {
                QCode::VerifiedIgate | QCode::RemoteIgate => Some(QCode::GatedClientOnly),
                QCode::Server | QCode::VerifiedClient => Some(QCode::NonGated),
                _ => None,
            };
            if let Some(code) = downgraded {
                return Ok(replace_at(path, found.offset, code, ctx.login));
            }
            return Ok(unchanged(path, found.code));
        }
        return Ok(append(path, QCode::NonGated, ctx.login));
    }

    // An already-tagged packet from the logged-in station keeps its construct: the entry
    // point has already been recorded and re-tagging would erase it.
    if let Some(found) = existing {
        return Ok(unchanged(path, found.code));
    }

    // Rule 6 — the common case: a station beaconing its own position.
    let code = if ctx.send_only {
        QCode::NonGated
    } else {
        QCode::VerifiedClient
    };
    Ok(append(path, code, ctx.server_id))
}

fn unchanged(path: Path<'_>, code: QCode) -> QOutcome {
    QOutcome {
        code,
        path: path.as_str().to_owned(),
        rewritten: false,
    }
}

fn append(path: Path<'_>, code: QCode, call: &str) -> QOutcome {
    let base = path.as_str();
    let new_path = if base.is_empty() {
        format!("{code},{call}")
    } else {
        format!("{base},{code},{call}")
    };
    QOutcome {
        code,
        path: new_path,
        rewritten: true,
    }
}

fn replace_at(path: Path<'_>, offset: usize, code: QCode, call: &str) -> QOutcome {
    let head = path.truncated_to(offset);
    let new_path = if head.is_empty() {
        format!("{code},{call}")
    } else {
        format!("{head},{code},{call}")
    };
    QOutcome {
        code,
        path: new_path,
        rewritten: true,
    }
}

fn replace_or_append(
    path: Path<'_>,
    existing: Option<FoundQ<'_>>,
    code: QCode,
    call: &str,
) -> QOutcome {
    match existing {
        Some(found) => replace_at(path, found.offset, code, call),
        None => append(path, code, call),
    }
}

/// Rewrite a trailing `,VIACALL,I` pair into `,<code>,VIACALL`.
fn rewrite_i_construct(path: Path<'_>, code: QCode, igate: &str) -> QOutcome {
    // The IGate callsign is the second-to-last hop; truncate the path there and append
    // the construct in its place.
    let mut offsets = path.hops().map(|h| h.offset).collect::<Vec<_>>();
    offsets.pop(); // the literal `I`
    let igate_offset = offsets.pop().unwrap_or(0);
    replace_at(path, igate_offset, code, igate)
}

#[cfg(test)]
mod tests {
    use super::*;
    use rstest::rstest;

    const SERVER: &str = "T2TEST";

    fn ctx(login: &str) -> QContext<'_> {
        QContext {
            server_id: SERVER,
            login,
            verified: true,
            via_udp: false,
            send_only: false,
        }
    }

    fn apply(raw: &str, ctx: &QContext<'_>) -> Result<QOutcome, QReject> {
        let packet = Tnc2Packet::parse(raw).expect("test packets are well formed");
        apply_client(&packet, ctx)
    }

    #[rstest]
    #[case("qAC", QCode::VerifiedClient)]
    #[case("qAX", QCode::Unverified)]
    #[case("qAU", QCode::Udp)]
    #[case("qAo", QCode::GatedClientOnly)]
    #[case("qAO", QCode::NonGated)]
    #[case("qAS", QCode::Server)]
    #[case("qAr", QCode::RemoteIgate)]
    #[case("qAR", QCode::VerifiedIgate)]
    #[case("qAZ", QCode::Internal)]
    #[case("qAI", QCode::Trace)]
    fn codes_roundtrip(#[case] wire: &str, #[case] code: QCode) {
        assert_eq!(QCode::parse(wire), Some(code));
        assert_eq!(code.as_str(), wire);
    }

    /// `qAo` and `qAO` differ only in case and mean different things, so parsing must be
    /// case-sensitive.
    #[test]
    fn code_parsing_is_case_sensitive() {
        assert_ne!(QCode::parse("qAo"), QCode::parse("qAO"));
        assert_eq!(QCode::parse("QAC"), None);
        assert_eq!(QCode::parse("qac"), None);
        assert_eq!(QCode::parse("WIDE1-1"), None);
    }

    #[test]
    fn finds_construct_and_following_call() {
        let path = Path::new("TCPIP*,qAC,T2FINLAND");
        let found = find(path).expect("qAC present");
        assert_eq!(found.code, QCode::VerifiedClient);
        assert_eq!(found.call, Some("T2FINLAND"));
        assert_eq!(path.truncated_to(found.offset), "TCPIP*");
    }

    // --- Rule 6: the common case -------------------------------------------------

    #[test]
    fn verified_client_beaconing_gets_qac_with_the_server_id() {
        let out = apply("N0CALL>APRS,TCPIP*:=6012.30N/02456.78E-", &ctx("N0CALL")).unwrap();
        assert_eq!(out.code, QCode::VerifiedClient);
        assert_eq!(out.path, "TCPIP*,qAC,T2TEST");
        assert!(out.rewritten);
    }

    #[test]
    fn qac_is_appended_even_when_the_path_is_empty() {
        let out = apply("N0CALL>APRS:>status", &ctx("N0CALL")).unwrap();
        assert_eq!(out.path, "qAC,T2TEST");
    }

    #[test]
    fn ssid_differences_make_the_fromcall_a_different_station() {
        // N0CALL-1 logging in and sending as N0CALL is relaying, not beaconing.
        let out = apply("N0CALL>APRS,TCPIP*:>status", &ctx("N0CALL-1")).unwrap();
        assert_eq!(out.code, QCode::NonGated);
        assert_eq!(out.path, "TCPIP*,qAO,N0CALL-1");
    }

    #[test]
    fn send_only_port_gets_qao_with_the_server_id() {
        let mut c = ctx("N0CALL");
        c.send_only = true;
        let out = apply("N0CALL>APRS,TCPIP*:>status", &c).unwrap();
        assert_eq!(out.code, QCode::NonGated);
        assert_eq!(out.path, "TCPIP*,qAO,T2TEST");
    }

    // --- Rule 2 and 3 ------------------------------------------------------------

    #[test]
    fn udp_entry_gets_qau() {
        let mut c = ctx("N0CALL");
        c.via_udp = true;
        let out = apply("N0CALL>APRS,TCPIP*:>status", &c).unwrap();
        assert_eq!(out.code, QCode::Udp);
        assert_eq!(out.path, "TCPIP*,qAU,T2TEST");
    }

    #[test]
    fn udp_entry_replaces_an_existing_construct() {
        let mut c = ctx("N0CALL");
        c.via_udp = true;
        let out = apply("N0CALL>APRS,TCPIP*,qAS,OTHER:>status", &c).unwrap();
        assert_eq!(out.path, "TCPIP*,qAU,T2TEST");
    }

    #[test]
    fn unverified_connection_gets_qax() {
        let mut c = ctx("N0CALL");
        c.verified = false;
        let out = apply("N0CALL>APRS,TCPIP*:>status", &c).unwrap();
        assert_eq!(out.code, QCode::Unverified);
        assert_eq!(out.path, "TCPIP*,qAX,T2TEST");
    }

    // --- Rule 4: the `,I` construct ----------------------------------------------

    #[test]
    fn i_construct_from_the_logged_in_igate_becomes_qar() {
        let out = apply("W1ABC>APRS,WIDE2-1,N0GATE,I:>rf packet", &ctx("N0GATE")).unwrap();
        assert_eq!(out.code, QCode::VerifiedIgate);
        assert_eq!(out.path, "WIDE2-1,qAR,N0GATE");
    }

    #[test]
    fn i_construct_from_another_igate_becomes_qar_lowercase() {
        let out = apply("W1ABC>APRS,WIDE2-1,N0GATE,I:>rf packet", &ctx("RELAYSRV")).unwrap();
        assert_eq!(out.code, QCode::RemoteIgate);
        assert_eq!(out.path, "WIDE2-1,qAr,N0GATE");
    }

    #[test]
    fn i_construct_with_no_other_hops() {
        let out = apply("W1ABC>APRS,N0GATE,I:>rf packet", &ctx("N0GATE")).unwrap();
        assert_eq!(out.path, "qAR,N0GATE");
    }

    // --- Rule 5: relaying somebody else's packet ---------------------------------

    #[rstest]
    #[case("qAR", QCode::GatedClientOnly, "qAo")]
    #[case("qAr", QCode::GatedClientOnly, "qAo")]
    #[case("qAS", QCode::NonGated, "qAO")]
    #[case("qAC", QCode::NonGated, "qAO")]
    fn existing_construct_is_downgraded_when_fromcall_differs(
        #[case] incoming: &str,
        #[case] expected_code: QCode,
        #[case] expected_wire: &str,
    ) {
        let raw = format!("W1ABC>APRS,TCPIP*,{incoming},SOMEONE:>relayed");
        let out = apply(&raw, &ctx("N0GATE")).unwrap();
        assert_eq!(out.code, expected_code);
        assert_eq!(out.path, format!("TCPIP*,{expected_wire},N0GATE"));
    }

    #[test]
    fn relaying_with_no_construct_appends_qao_with_the_client_login() {
        let out = apply("W1ABC>APRS,WIDE1-1:>relayed", &ctx("N0GATE")).unwrap();
        assert_eq!(out.code, QCode::NonGated);
        assert_eq!(out.path, "WIDE1-1,qAO,N0GATE");
    }

    /// A construct that is not in the downgrade table is left alone rather than guessed at.
    #[test]
    fn unlisted_construct_passes_through_when_relaying() {
        let out = apply("W1ABC>APRS,TCPIP*,qAU,OTHER:>relayed", &ctx("N0GATE")).unwrap();
        assert_eq!(out.code, QCode::Udp);
        assert_eq!(out.path, "TCPIP*,qAU,OTHER");
        assert!(!out.rewritten);
    }

    /// An IGate that already tagged its own packet keeps that tag.
    #[test]
    fn own_packet_with_existing_construct_is_untouched() {
        let out = apply("N0GATE>APRS,TCPIP*,qAR,N0GATE:>beacon", &ctx("N0GATE")).unwrap();
        assert_eq!(out.code, QCode::VerifiedIgate);
        assert!(!out.rewritten);
    }

    // --- Rule 1: rejection --------------------------------------------------------

    #[test]
    fn qaz_is_rejected() {
        let err = apply("N0CALL>APRS,TCPIP*,qAZ,T2OTHER:>internal", &ctx("N0CALL")).unwrap_err();
        assert_eq!(err, QReject::Internal);
    }

    #[test]
    fn qac_without_a_tcpip_marker_is_rejected() {
        let err = apply("N0CALL>APRS,WIDE1-1,qAC,T2OTHER:>bogus", &ctx("N0CALL")).unwrap_err();
        assert_eq!(err, QReject::QacWithoutTcpip);
    }

    #[test]
    fn our_own_server_id_after_the_construct_is_a_loop() {
        let err = apply("N0CALL>APRS,TCPIP*,qAC,T2TEST:>looped", &ctx("N0CALL")).unwrap_err();
        assert_eq!(
            err,
            QReject::Loop {
                server_id: SERVER.to_owned()
            }
        );
    }

    #[test]
    fn a_repeated_callsign_in_the_path_is_a_loop() {
        let err = apply("N0CALL>APRS,N0GATE,WIDE2-1,N0GATE:>looped", &ctx("N0CALL")).unwrap_err();
        assert_eq!(
            err,
            QReject::DuplicateInPath {
                call: "N0GATE".to_owned()
            }
        );
    }

    /// Routing aliases legitimately repeat and must not be mistaken for a loop.
    #[test]
    fn repeated_routing_aliases_are_not_a_loop() {
        assert!(apply("N0CALL>APRS,WIDE1-1,WIDE2-1:>ok", &ctx("N0CALL")).is_ok());
    }

    // --- Round-trip ---------------------------------------------------------------

    #[test]
    fn outcome_path_produces_a_reparseable_packet() {
        let raw = "N0CALL>APRS,TCPIP*:=6012.30N/02456.78E-Testing";
        let packet = Tnc2Packet::parse(raw).unwrap();
        let out = apply_client(&packet, &ctx("N0CALL")).unwrap();
        let rendered = packet.with_path(&out.path);
        let reparsed = Tnc2Packet::parse(&rendered).expect("rewritten packet must be valid");
        assert_eq!(reparsed.source(), "N0CALL");
        assert_eq!(reparsed.payload(), packet.payload());
        assert_eq!(find(reparsed.path()).unwrap().code, QCode::VerifiedClient);
    }

    proptest::proptest! {
        /// The algorithm runs on adversarial input and must never panic.
        #[test]
        fn apply_never_panics(
            src in "[A-Z0-9-]{1,9}",
            path in "[A-Za-z0-9*,-]{0,60}",
            payload in "[ -~]{1,40}",
            verified in proptest::bool::ANY,
            via_udp in proptest::bool::ANY,
        ) {
            let raw = format!("{src}>APRS,{path}:{payload}");
            let Ok(packet) = Tnc2Packet::parse(&raw) else { return Ok(()) };
            let c = QContext {
                server_id: SERVER,
                login: "N0CALL",
                verified,
                via_udp,
                send_only: false,
            };
            let _ = apply_client(&packet, &c);
        }

        /// Whenever the algorithm accepts a packet, the resulting path must still form a
        /// parseable packet — dispatch relies on this to re-render without re-validating.
        #[test]
        fn accepted_paths_stay_parseable(
            src in "[A-Z0-9]{1,6}",
            path in "(TCPIP\\*|WIDE1-1|WIDE2-2)(,(TCPIP\\*|WIDE1-1|WIDE2-2)){0,3}",
            payload in "[ -~]{1,40}",
        ) {
            let raw = format!("{src}>APRS,{path}:{payload}");
            let Ok(packet) = Tnc2Packet::parse(&raw) else { return Ok(()) };
            let Ok(out) = apply_client(&packet, &ctx("N0CALL")) else { return Ok(()) };
            let rendered = packet.with_path(&out.path);
            proptest::prop_assert!(Tnc2Packet::parse(&rendered).is_ok(), "{rendered}");
        }
    }
}
